# Generated by Django 3.2 on 2024-05-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='indian_currency',
            new_name='indian_currency',
        ),
    ]
